nelmio_api_doc:
    documentation:
        info:
            title: AeroFlow Core API
            description: API for AeroFlow core business service.
            version: 1.0.0
    areas:
        default:
            path_patterns:
                - ^/api/v1(?!/doc)
