security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        App\UserAccess\Domain\Entity\User: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_jwt_provider:
            id: App\UserAccess\Infrastructure\Security\JwtUserProvider

    firewalls:
        dev:
            # Ensure dev tools and static assets are always allowed
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        main:
            stateless: true
            provider: app_jwt_provider
            jwt: ~

    # Note: Only the *first* matching rule is applied
    access_control:
        - { path: ^/api/v1/register$, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1/login$, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1/token/refresh$, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1/logout$, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            # Password hashers are resource-intensive by design to ensure security.
            # In tests, it's safe to reduce their cost to improve performance.
            App\UserAccess\Domain\Entity\User:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
