# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    user_access.refresh_token_ttl: '+30 days'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\UserAccess\Domain\Repository\UserRepositoryInterface:
        alias: App\UserAccess\Infrastructure\Persistance\Doctrine\UserRepository

    App\UserAccess\Domain\Repository\RefreshTokenRepositoryInterface:
        alias: App\UserAccess\Infrastructure\Persistance\Doctrine\RefreshTokenRepository

    App\UserAccess\Application\Security\AccessTokenIssuerInterface:
        alias: App\UserAccess\Infrastructure\Security\LexikAccessTokenIssuer

    App\UserAccess\Application\Security\RefreshTokenGeneratorInterface:
        alias: App\UserAccess\Infrastructure\Security\RandomRefreshTokenGenerator

    App\UserAccess\Application\Security\RefreshTokenHasherInterface:
        alias: App\UserAccess\Infrastructure\Security\Sha256RefreshTokenHasher

    App\FlightOperations\Domain\Repository\FlightDefinitionRepositoryInterface:
        alias: App\FlightOperations\Infrastructure\Persistence\Doctrine\FlightDefinitionRepository

    App\FlightOperations\Application\ListFlightDefinitions\FlightDefinitionListQueryInterface:
        alias: App\FlightOperations\Infrastructure\Persistence\Doctrine\DbalFlightDefinitionListQuery

    App\FlightOperations\Domain\Repository\AirportRepositoryInterface:
        alias: App\FlightOperations\Infrastructure\Persistence\Doctrine\AirportRepository

    App\FlightOperations\Application\ListAirports\AirportListQueryInterface:
        alias: App\FlightOperations\Infrastructure\Persistence\Doctrine\DbalAirportListQuery
